uap_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('POSTGRES_USER', 'dagster') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dagster') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'dagster') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      threads: 4
